### ISSUE TITLE
[Feature] Color Wheel Activity / Gradient

### ISSUE THREAD

**Issue by not-fritos** [codewithher/CC-Library-Lantern#14]
## Description

Currently our library of activities and examples don't goes through the entire color gradient. 

The goal of this feature request is to have vertical ownership over the creation process of a new activity from code to lesson plan.

For now, replace the existing "gradient" functions in `act3-functions` with a `rainbow()` as the function.

Requirements:
- [x] Rewrite and remove existing gradient examples in `activities/act3` to use `colorWheel()`
- [x] Ensure rainbow function take in `(duration, speed (optional))` as parameters
- [x] Add a comment to this issue with testing instructions
- [ ] Edit existing [act3 page on notion](https://www.notion.so/Mix-and-match-your-magic-8795f54d2ea84a2580a586d4e57de652?pvs=4) to focus on gradients
  - Content contribution guide will be created in the future
  - Currently the lesson plan focuses on function readability. See if you can balance between that and gradients
  - Use a [readability test](https://www.webfx.com/tools/read-able/) to check readability
  - Use pictures where possible
  - Use small words as often as possible. Opt for shorter sentences when possible.
  - Use double spacing where possible
  - Keep pages to be strictly on topic, if there's another concept to discuss, write that in a new place

## Additional Notes
- Will need accompanying example files
- Each requirement should be handled as a sub-branch

**Comment by innaamogolonova** [comment]
** Testing Instructions**

The easiest way to test is to run the rainbow method in activity 3 which double as testing files. 

You can verify that the code works appropriately by visually inspecting the colors that result from the activity function calls.

- [ ] The LED goes through the complete color spectrum (red to green to blue back to red)
- [ ] The color change is gradual and smooth 
- [ ] The rainbow lasts the specified "seconds" amount of time

**Comment by not-fritos** [comment]
closed in #15
